# Generated by Django 5.1.7 on 2025-05-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_time_alter_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
