# Generated by Django 5.1.7 on 2025-04-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('cpf', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
